#include "ProtozoaApp.h"
#include "Moose.h"
#include "AppFactory.h"

template<>
InputParameters validParams<ProtozoaApp>()
{
  InputParameters params = validParams<MooseApp>();
  return params;
}

ProtozoaApp::ProtozoaApp(const std::string & name, InputParameters parameters) :
    MooseApp(name, parameters)
{
  srand(libMesh::processor_id());
  
  Moose::registerObjects(_factory);
  ProtozoaApp::registerObjects(_factory);

  Moose::associateSyntax(_syntax, _action_factory);
  ProtozoaApp::associateSyntax(_syntax, _action_factory);
}

ProtozoaApp::~ProtozoaApp()
{
}

void
ProtozoaApp::registerApps()
{
  registerApp(ProtozoaApp);
}

void
ProtozoaApp::registerObjects(Factory & factory)
{
}

void
ProtozoaApp::associateSyntax(Syntax & syntax, ActionFactory & action_factory)
{
}
